.TH raylib 3 2024-12-28 v5.6
.SH NAME
.B raylib 
\- a simple and easy-to-use library to enjoy videogames programming
.SH SYNOPSIS
.B #include <raylib.h>
.SH DESCRIPTION
The raylib library is written in plain C code (C99), 
with bindings to multiple languages and multiplatform support. 
It is designed with simplicity and ease of use in mind, 
with no external dependencies,
and several submodules that may be used independently.
